{
  imports = [
    ./lualine.nix
    ./mini
    ./gitsigns.nix
    ./telescope.nix
    ./which-key.nix
    ./yazi.nix
    ./neo-tree.nix
    ./bufferline.nix
    ./noice.nix
    ./lsp.nix
    ./conform.nix
    ./project-nvim.nix
    ./snacks.nix
    ./toogleterm.nix
    ./compiler.nix
    ./blink-cmp.nix
    ./codeium.nix
    ./helpview.nix
    ./hmts.nix
    ./illuminate.nix
    ./lightbulb.nix
    ./nix.nix
    ./overseer.nix
    ./sleuth.nix
    ./smartcolumn.nix
    ./todo.nix
    ./treesitter.nix
    ./ts-comments.nix
    ./wakatime.nix
    ./trouble.nix
  ];
}
