{
  imports = [
    ./lualine.nix
    ./mini
    ./gitsigns.nix
    ./telescope.nix
    ./which-key.nix
    ./yazi.nix
    ./neo-tree.nix
    ./bufferline.nix
    ./noice.nix
    ./lsp.nix
    ./cmp.nix
    ./conform.nix
    ./project-nvim.nix
    ./snacks.nix
    ./toogleterm.nix
  ];
}
